namespace Questions;

internal class Program
{
   static void Main(string[] args)
   {
      _Questions._Main.Ex01();
      _Questions._Main.Ex02();
      _Questions._Main.Ex03();
      _Questions._Main.Ex04();
      _Questions._Main.Ex05();
      _Questions._Main.Ex06();
      _Questions._Main.Ex07();
      _Questions._Main.Ex08();
      _Questions._Main.Ex09();
      _Questions._Main.Ex10();
      _Questions._Main.Ex11();
      _Questions._Main.Ex12();
      _Questions._Main.Ex13();
      _Questions._Main.Ex14();
      _Questions._Main.Ex15();
      _Questions._Main.Ex16();
      _Questions._Main.Ex17();
      _Questions._Main.Ex18();
      _Questions._Main.Ex19();
      _Questions._Main.Ex20();
      _Questions._Main.Ex21();
      _Questions._Main.Ex22();
      _Questions._Main.Ex23();
      _Questions._Main.Ex24();
      _Questions._Main.Ex25();
      _Questions._Main.Ex26();
      _Questions._Main.Ex27();
      _Questions._Main.Ex28();
      _Questions._Main.Ex29();
      _Questions._Main.Ex30();
      _Questions._Main.Ex31();
      _Questions._Main.Ex32();
      _Questions._Main.Ex33();
      _Questions._Main.Ex34();
      _Questions._Main.Ex35();
      _Questions._Main.Ex36();
      _Questions._Main.Ex37();
      _Questions._Main.Ex38();
      _Questions._Main.Ex39();
      _Questions._Main.Ex40();
      _Questions._Main.Ex41();
      _Questions._Main.Ex42();
      _Questions._Main.Ex43();
      _Questions._Main.Ex44();
      _Questions._Main.Ex45();
      _Questions._Main.Ex46();
      _Questions._Main.Ex47();
      _Questions._Main.Ex48();
      _Questions._Main.Ex49();
      _Questions._Main.Ex50();
      _Questions._Main.Ex51();
      _Questions._Main.Ex52();
      _Questions._Main.Ex53();
      _Questions._Main.Ex54();
      _Questions._Main.Ex55();
      _Questions._Main.Ex56();

   }
}
